language: php
php:
  - 5.5
  - 5.4
  - 5.3
# Always get the latest composer to avoid errors.
before_script: curl -sS https://getcomposer.org/installer | php
script: php composer.phar install; vendor/bin/phpunit -c Tests/phpunit.xml
